In [1]:
# Notebook for looking at MovieLens Latest data
# Dataframe loaded from MovieLens Latest data processed through script in preprocessing2.py

In [2]:
import pandas as pd
import numpy as np
import cPickle as pickle

In [3]:
with open('../data/ml-latest_df.pkl') as f:
    movie_df = pickle.load(f)

In [4]:
movie_df.head(50)

,movieId,imdbId,title,year,tags,tags_length
0,1,114709,Toy Story,1995,"[cute, bd-video, 55_movies_every_kid_should_se...",118
1,2,113497,Jumanji,1995,"[family, baker_viu, fantasy, saturn_award_(bes...",44
2,3,113228,Grumpier Old Men,1995,"[funny, sequel_fever, comedy, old, walter_matt...",18
3,4,114885,Waiting to Exhale,1995,"[Romance, girl_movie, revenge, chick_flick, Dr...",8
4,5,113041,Father of the Bride Part II,1995,"[sequel_fever, sequel, family, childhood_class...",18
5,6,113277,Heat,1995,"[rob, Crime, violent, visceral, relationships,...",100
6,7,114319,Sabrina,1995,"[remakeof:sabrina(1954), great_cast, Romance, ...",26
7,8,112302,Tom and Huck,1995,"[mark_twain, disney, Adventure, peter_hewitt, ...",9
8,9,114576,Sudden Death,1995,"[can't_remember, jean-claude_van_damme, action...",6
9,10,113189,GoldenEye,1995,"[classic, bd-video, owned, it's_a_good_movie_b...",52
10,11,112346,"American President, The",1995,"[cute, morals, great_cast, Romance, bibliothek...",33
11,12,112896,Dracula: Dead and Loving It,1995,"[funny, vampires, farce, leslie_nielsen, borin...",13
12,13,112453,Balto,1995,"[sled_dogs, dogsled, itaege, simon_wells, Chil...",13
13,14,113987,Nixon,1995,"[watergate, own, wooohoo, politics, biography,...",23
14,15,112760,Cutthroat Island,1995,"[big_budget, geena_davis, bad_acting, humor, b...",18
15,16,112641,Casino,1995,"[erlend's_dvds, violence, non-fiction, muddled...",64
16,17,114388,Sense and Sensibility,1995,"[period_piece, hugh_grant, classic, trials_and...",60
17,18,113101,Four Rooms,1995,"[tarantino, own, multiple_short_stories_in_one...",30
18,19,112281,Ace Ventura: When Nature Calls,1995,"[detective, crazy, hehehe, simple, awesome, on...",28
19,20,113845,Money Train,1995,"[intense, worthwhile, lame, money, joseph_rube...",14
20,21,113161,Get Shorty,1995,"[author:elmore_leonard, forgetable, Crime, hil...",30
21,22,112722,Copycat,1995,"[Mystery, detective, strong_female_lead, detec...",18
22,23,112401,Assassins,1995,"[sylvester_stallone, divx1, Crime, afternoon_s...",12
23,24,114168,Powder,1995,"[tearjerking, Sci-Fi, elegiac, special_powers,...",19
24,25,113627,Leaving Las Vegas,1995,"[bittersweet, elisabeth_shue, love, elegiac, l...",54
25,26,114057,Othello,1995,"[great, wow, ei_muista, based_on_a_play, Drama...",12
26,27,114011,Now and Then,1995,"[bechdel_test:pass, brendan_fraser, christina_...",22
27,28,114117,Persuasion,1995,"[period_piece, england, Romance, bland, adapta...",32
28,29,112682,"City of Lost Children, The (Cité des enfants p...",1995,"[whimsical, beautiful, Sci-Fi, deer_shit, circ...",55
29,30,115012,Shanghai Triad (Yao a yao yao dao waipo qiao),1995,"[Drama, gong_li, yimou_zhang, zhang_yimou, Crime]",5
30,31,112792,Dangerous Minds,1995,"[own, awesome, dead, school_drama, nigga, bibl...",36
31,32,114746,Twelve Monkeys (a.k.a. 12 Monkeys),1995,"[sci_fi, excellent, divx1, ending, science_fic...",116
32,33,114952,Wings of Courage,1995,"[Romance, stereoscopic_3-d, imax_3-d, Adventur...",5
33,34,112431,Babe,1995,"[cute, own, rats, family, sweet, infantil, hug...",47
34,35,112637,Carrington,1995,"[england, world_war_i, bisexual, bloomsbury_gr...",25
35,36,112818,Dead Man Walking,1995,"[oscar_(best_actress), deaf, usa, Crime, nun, ...",54
36,37,112286,Across the Sea of Time,1995,"[imax_3-d, stereoscopic_3-d, Documentary, IMAX...",5
37,38,113442,It Takes Two,1995,"[cute, heartwarming, switching_places, nostalg...",11
38,39,112697,Clueless,1995,"[inspired_by_jane_austen, fashion, saw_it_ten_...",56
39,40,112749,"Cry, the Beloved Country",1995,"[in_netflix_queue, south_africa, africa, racis...",9
40,41,114279,Richard III,1995,"[adapted_from:play, dvd-ram, robert_downey_jr,...",14
41,42,112819,Dead Presidents,1995,"[vietnam_war, eric's_dvds, crime, Drama, bank_...",10
42,43,114272,Restoration,1995,"[period_piece, england, Drama, historical, nud...",7
43,44,113855,Mortal Kombat,1995,"[faithful_to_game, bad_acting, no_fatalities, ...",38
44,45,114681,To Die For,1995,"[clearplay, wayne_knight, erlend's_dvds, journ...",16
45,46,113347,How to Make an American Quilt,1995,"[Romance, bibliothek, Drama, nudity_(topless_-...",9
46,47,114369,Seven (a.k.a. Se7en),1995,"[detective, spacey:_excellent....pitt:_brillia...",143
47,48,114148,Pocahontas,1995,"[not_according_to_the_truth, mel_gibson, stron...",52
48,49,114916,When Night Is Falling,1995,"[Romance, own, atmospheric, visually_appealing...",14
49,50,114814,"Usual Suspects, The",1995,"[detective, atmosphere, nonlinear_storyline, b...",153

In [5]:
movie_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45843 entries, 0 to 45842
Data columns (total 6 columns):
movieId        45843 non-null int64
imdbId         45843 non-null int64
title          45843 non-null object
year           45843 non-null object
tags           45843 non-null object
tags_length    45843 non-null int64
dtypes: int64(3), object(3)
memory usage: 2.4+ MB

In [6]:
movie_df.describe()

             movieId        imdbId   tags_length
count   45843.000000  4.584300e+04  45843.000000
mean    96578.775626  9.937080e+05      7.553716
std     57216.863469  1.361924e+06     14.799626
min         1.000000  1.000000e+00      1.000000
25%     49202.500000  8.333050e+04      2.000000
50%    108799.000000  2.839910e+05      3.000000
75%    145270.500000  1.538311e+06      7.000000
max    176279.000000  7.158814e+06    938.000000

In [7]:
# Notes:
# ------
# To get an index for a particular movie:
# > movie_df.loc[movie_df.title == 'Godfather, The'].index[0]
# > 843

# To get a movie at a particular index:
# > movie_df.title.loc[99]
# > 'Bottle Rocket'

In [8]:
# Test Movies

In [9]:
movie_df.loc[movie_df.title == 'A.I. Artificial Intelligence'].index[0]

4276

In [10]:
movie_df.loc[movie_df.title == 'Lost in Translation'].index[0]

6602

In [11]:
movie_df.loc[movie_df.title == 'Her'].index[0]

22396

In [12]:
movie_df.loc[movie_df.title == 'Ray'].index[0]

8275

In [13]:
movie_df.loc[movie_df.title == 'Raging Bull'].index[0]

1202

In [14]:
movie_df.loc[movie_df.title == 'Whiplash'].index[0]

23945

In [15]:
movie_df.loc[movie_df.title == 'Twelve Monkeys (a.k.a. 12 Monkeys)'].index[0]

31

In [16]:
movie_df.loc[movie_df.title == 'Seven (a.k.a. Se7en)'].index[0]

46

In [17]:
movie_df.loc[movie_df.title == 'Grudge, The'].index[0]

8264

In [18]:
movie_df.loc[movie_df.title == 'American Pie'].index[0]

2621

In [19]:
movie_df.loc[movie_df.title == "Casino Royale"]

,movieId,imdbId,title,year,tags,tags_length
5698,5796,61452,Casino Royale,1967,"[crazy, peter_sellers, related:007_(series), A...",25
11467,49272,381061,Casino Royale,2006,"[daniel_craig, bd-video, eva_green, london, hu...",97

In [20]:
def show_tags(movie):
    '''
    Takes in a string of a movie title, prints the tags for that movie.
    '''
    movie_idx = movie_df.loc[movie_df.title == movie].index[0]
    movie_tags = movie_df.tags.loc[movie_idx]
    for tag in movie_tags:
        print tag
    return movie_tags

In [21]:
show_tags('Queerama')

united_kingdom
britain
documentary
homosexuality
(no_genres_listed)

['united_kingdom',
 'britain',
 'documentary',
 'homosexuality',
 '(no_genres_listed)']

In [22]:
show_tags('Nieve negra')

leonardo_sbaraglia
ricardo_darin
Thriller

['leonardo_sbaraglia', 'ricardo_darin', 'Thriller']

In [38]:
show_tags('When Harry Met Sally...')

friendzone
cute
friendship_of_love
romantic_speech
netflix_finland
romance.
classic
bd-video
Romance
bechdel_test:fail
nora_ephron
traveling
afi_100_(laughs)
veja
ownable
Comedy
cheesy
best_friends_fall_in_love
funny
afi_100_(movie_quotes)
weihnachtsfilm
meg_ryan
chicago
quotable
friends_vs_lovers
chick_flick
romance
1980s
bruno_kirby
rom-com
talking_on_phone
clv
carrie_fisher
unlikely_friendships
smart
relationships
dialogue
no_fa_ganes
i_own_this
famous_scene
romantic_comedy
jazz
sunny
girlie_movie
soundtrack
watched_2006
billy_crystal
r
new_york
rob_reiner
i_know_every_word_by_heart
romantic
seealso:when_harry_met_sally_(1989)
youtube
oscar_nominee
seen_more_than_once
new_year_eve
meeting_again_and_again
one_of_the_funniest_movies_ever.
good_romantic_comedies
meg_fake_orgasm
ripped_off_annie_hall
fun
friendship
character_development
the_quintessential_romantic_comedy!

['friendzone',
 'cute',
 'friendship_of_love',
 'romantic_speech',
 'netflix_finland',
 'romance.',
 'classic',
 'bd-video',
 'Romance',
 'bechdel_test:fail',
 'nora_ephron',
 'traveling',
 'afi_100_(laughs)',
 'veja',
 'ownable',
 'Comedy',
 'cheesy',
 'best_friends_fall_in_love',
 'funny',
 'afi_100_(movie_quotes)',
 'weihnachtsfilm',
 'meg_ryan',
 'chicago',
 'quotable',
 'friends_vs_lovers',
 'chick_flick',
 'romance',
 '1980s',
 'bruno_kirby',
 'rom-com',
 'talking_on_phone',
 'clv',
 'carrie_fisher',
 'unlikely_friendships',
 'smart',
 'relationships',
 'dialogue',
 'no_fa_ganes',
 'i_own_this',
 'famous_scene',
 'romantic_comedy',
 'jazz',
 'sunny',
 'girlie_movie',
 'soundtrack',
 'watched_2006',
 'billy_crystal',
 'r',
 'new_york',
 'rob_reiner',
 'i_know_every_word_by_heart',
 'romantic',
 'seealso:when_harry_met_sally_(1989)',
 'youtube',
 'oscar_nominee',
 'seen_more_than_once',
 'new_year_eve',
 'meeting_again_and_again',
 'one_of_the_funniest_movies_ever.',
 'good_romantic_comedies',
 'meg_fake_orgasm',
 'ripped_off_annie_hall',
 'fun',
 'friendship',
 'character_development',
 'the_quintessential_romantic_comedy!']

In [24]:
movie_df.loc[movie_df.title == 'Avengers, The']

,movieId,imdbId,title,year,tags,tags_length
2070,2153,118661,"Avengers, The",1998,"[ralph_fiennes, based_on_a_tv_show, sean_conne...",11
17941,89745,848228,"Avengers, The",2012,"[shield, bd-video, gods, 55_movies_every_kid_s...",167

In [25]:
movie_df.loc[movie_df.title == "Harry Potter*"]

Empty DataFrame
Columns: [movieId, imdbId, title, year, tags, tags_length]
Index: []

In [26]:
movie_df.loc[movie_df.title.str.contains('Avengers, The')]

,movieId,imdbId,title,year,tags,tags_length
2070,2153,118661,"Avengers, The",1998,"[ralph_fiennes, based_on_a_tv_show, sean_conne...",11
17941,89745,848228,"Avengers, The",2012,"[shield, bd-video, gods, 55_movies_every_kid_s...",167

In [27]:
movie_df.loc[movie_df.title.str.contains('Harry Potter')]

,movieId,imdbId,title,year,tags,tags_length
4801,4896,241527,Harry Potter and the Sorcerer's Stone (a.k.a. ...,2001,"[cute, book_adaptation, divx1, children, famil...",109
5718,5816,295297,Harry Potter and the Chamber of Secrets,2002,"[own, england, book_was_better, potter, divx1,...",63
7769,8368,304141,Harry Potter and the Prisoner of Azkaban,2004,"[erlend's_dvds, own, pseudo_rated, potter, div...",63
10614,40815,330373,Harry Potter and the Goblet of Fire,2005,"[atrocious_editing, dance, divx1, jus+san, gos...",87
11992,54001,373889,Harry Potter and the Order of the Phoenix,2007,"[beautiful, own, saga, too_short, good_vs._evi...",51
13969,69844,417741,Harry Potter and the Half-Blood Prince,2009,"[own, series, teenagers, ending, Romance, fant...",70
16239,81834,926084,Harry Potter and the Deathly Hallows: Part 1,2010,"[bechdel_test:pass, evanna_lynch, london, netf...",94
17559,88125,1201607,Harry Potter and the Deathly Hallows: Part 2,2011,"[teen, alexandre_desplat, end_of_a_series, wri...",52

In [28]:
# Way to search for the exact movie title in the dataframe if you don't know it
def search_title(search_string):
    result_df = movie_df.loc[movie_df.title.str.contains(search_string)]
    return result_df

In [37]:
search_title('Harry Met Sally')

,movieId,imdbId,title,year,tags,tags_length
1278,1307,98635,When Harry Met Sally...,1989,"[friendzone, cute, friendship_of_love, romanti...",66

In [30]:
search_title('Seven Samurai')

,movieId,imdbId,title,year,tags,tags_length
1936,2019,47478,Seven Samurai (Shichinin no samurai),1954,"[old_man, seven, bechdel_test:fail, janus_50, ...",79

In [31]:
# If you have 2 movie titles with the same name, maybe pick the movie that has more tags (longer tag length) -
# could correspond to higher popularity.
# Need to do in parse_input()

In [32]:
movie_df.tags_length.sum()

346285L

In [33]:
import preprocessing2

In [34]:
movies, links, tags, genome_tags, genome_scores = preprocessing2.get_data()

In [35]:
movies.head(50)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,11,"American President, The (1995)",Comedy|Drama|Romance
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
12,13,Balto (1995),Adventure|Animation|Children
13,14,Nixon (1995),Drama
14,15,Cutthroat Island (1995),Action|Adventure|Romance
15,16,Casino (1995),Crime|Drama
16,17,Sense and Sensibility (1995),Drama|Romance
17,18,Four Rooms (1995),Comedy
18,19,Ace Ventura: When Nature Calls (1995),Comedy
19,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller
20,21,Get Shorty (1995),Comedy|Crime|Thriller
21,22,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller
22,23,Assassins (1995),Action|Crime|Thriller
23,24,Powder (1995),Drama|Sci-Fi
24,25,Leaving Las Vegas (1995),Drama|Romance
25,26,Othello (1995),Drama
26,27,Now and Then (1995),Children|Drama
27,28,Persuasion (1995),Drama|Romance
28,29,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Crime|Drama
30,31,Dangerous Minds (1995),Drama
31,32,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller
32,33,Wings of Courage (1995),Adventure|Romance|IMAX
33,34,Babe (1995),Children|Drama
34,35,Carrington (1995),Drama|Romance
35,36,Dead Man Walking (1995),Crime|Drama
36,37,Across the Sea of Time (1995),Documentary|IMAX
37,38,It Takes Two (1995),Children|Comedy
38,39,Clueless (1995),Comedy|Romance
39,40,"Cry, the Beloved Country (1995)",Drama
40,41,Richard III (1995),Drama|War
41,42,Dead Presidents (1995),Action|Crime|Drama
42,43,Restoration (1995),Drama
43,44,Mortal Kombat (1995),Action|Adventure|Fantasy
44,45,To Die For (1995),Comedy|Drama|Thriller
45,46,How to Make an American Quilt (1995),Drama|Romance
46,47,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
47,48,Pocahontas (1995),Animation|Children|Drama|Musical|Romance
48,49,When Night Is Falling (1995),Drama|Romance
49,50,"Usual Suspects, The (1995)",Crime|Mystery|Thriller